[[plugins]]
  package = "./netlify/netlify-enable-proxy"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self' https://countriesnow.space https://*.stripe.com;
      connect-src *;
      img-src * 'self' data: https:;
      style-src 'unsafe-inline' 'self';
      frame-src https://*.stripe.com https://*.youtube.com https://youtube.com https://*.vimeo.com https://vimeo.com https://*.wistia.com https://wistia.com https://*.vidyard.com https://vidyard.com https://*.brightcove.net https://brightcove.net;
      frame-ancestors https://*.stripe.com https://*.youtube.com https://youtube.com https://*.vimeo.com https://vimeo.com https://*.wistia.com https://wistia.com https://*.vidyard.com https://vidyard.com https://*.brightcove.net https://brightcove.net
    '''
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin"
    Permissions-Policy = "payment=(self)"

[[redirects]]
  from = "/client-api/*"
  to = "https://client-api.openchannel.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
